[package]
name = "vector"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9"
raw-window-handle = "0.5.0"
cosmic-text = { path = "../../" }
glutin = "0.30.0"
femtovg = { version = "0.3.7", default-features = false }
winit = "0.27.5"
